### ISSUE TITLE
not able to connect to a meeitng

### ISSUE THREAD

**Issue by ashishranjan3** [RivaanRanawat/zoom-clone#2]
hey bro..

i was trying to integrate jisti meet in my app.. i after trying 4-5 days i was loosing hope as i was getting some eroor..

again i was searching on the google and found your code..after seeing this i though finally i will achieve this goal of mine..

bro plz help,,, i am getting this ugly error

E/AndroidRuntime(17819): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
E/AndroidRuntime(17819): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(17819): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(17819): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(17819): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17819): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(17819): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(17819): JitsiMeetUncaughtExceptionHandler FATAL ERROR
E/JitsiMeetSDK(17819): android.app.RemoteServiceException: Bad notification for startForeground
E/JitsiMeetSDK(17819): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
E/JitsiMeetSDK(17819): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(17819): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(17819): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(17819): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(17819): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(17819): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
E/JitsiMeetSDK(17819): 
E/JitsiMeetSDK(17819): android.app.RemoteServiceException: Bad notification for startForeground
E/JitsiMeetSDK(17819): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2005)
E/JitsiMeetSDK(17819): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/JitsiMeetSDK(17819): 	at android.os.Looper.loop(Looper.java:223)
E/JitsiMeetSDK(17819): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/JitsiMeetSDK(17819): 	at java.lang.reflect.Method.invoke(Native Method)
E/JitsiMeetSDK(17819): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/JitsiMeetSDK(17819): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process (17819): Sending signal. PID: 17819 SIG: 9
Lost connection to device.

**Comment by mansoor-saidu** [comment]
have you changed the firebase config

**Comment by RivaanRanawat** [comment]
Are you getting this error after cloning and running this repository or after integrating Jitsi Meet in your own app?
